### ISSUE TITLE
Proposal: getSnippets

### ISSUE THREAD

**Issue by magland** [colehurwitz31/spikeinterface#20]
Change

```
def getSnippets(self, snippet_len, center_frames, channel_ids=None):
```

to

```
def getSnippets(self, snippet_len_before, snippet_len_after, start_frames, channel_ids=None):
```
or something in order to accommodate asymmetric snippets.

**Comment by alejoe91** [comment]
@magland I agree

**Comment by magland** [comment]
@colehurwitz31 . This should be done soon so that we don't need to adjust too much of the tools that use the API.

**Comment by magland** [comment]
@colehurwitz31. I assigned this to myself.

**Comment by colehurwitz31** [comment]
I can do this now and upload it with my epoch changes unless you are already done

**Comment by magland** [comment]
I haven't worked on it yet, so you can go ahead. Thx!
