### ISSUE TITLE
getUnitSpikeTrain in NumpySortingExtractor and MDASortingExtractor return ints and floats respectively.

### ISSUE THREAD

**Issue by colehurwitz31** [colehurwitz31/spikeinterface#30]
It looks like MDASortingExtractor is returning a numpy array of floats (although frames should be ints)

**Comment by colehurwitz31** [comment]
This can be checked for with static typing which I aim to do this week

**Comment by magland** [comment]
Actually, I think it should return floats, since we can have events at times that don't line up with the time grid. This can happen, for example, if we upsample to get more precise detection.

**Comment by colehurwitz31** [comment]
I thought getunitSpikeTrains always returned frames which would not have any decimal values?

**Comment by magland** [comment]
It is units of frames, but you could have an event that occurs between two timepoints (timeframes), if the detection precision is greater than the sampling rate.

**Comment by colehurwitz31** [comment]
I see. So that is why getSnippets has integer wrappers around the center frames... that makes sense I guess. I find the concept of frames having decimal values to be confusing, but I understand the use case. So then NumpySortingExtractor should probably be updated to floats.

**Comment by magland** [comment]
Yeah, we do use this sometimes.

**Comment by colehurwitz31** [comment]
Ok, so we should make sure all extractors do what MDASortingExtractor does
