### ISSUE TITLE
Example notebooks broken

### ISSUE THREAD

**Issue by colehurwitz31** [colehurwitz31/spikeinterface#32]
Except for getting_started_with_recording_extractors and getting_started_with_sorting_extractors, the current example notebooks we have either are not updated or require data that isn't available.

For anyone who made a specific example for a file type, could you either update or remove the example?

**Comment by colehurwitz31** [comment]
The biocam and mearec examples are broken specifically so I assigned Alessio and Matthias to this issue. We will probably remove these examples anyway.

**Comment by alejoe91** [comment]
mearec is fixed 01a293daf06eaab9eb7c5f117d93e7f536c9a788

**Comment by colehurwitz31** [comment]
I'm going to remove the biocam example before release if it still doesn't work
