### ISSUE TITLE
Proposal: getSnippets -- replace snippet_len_before and snippet_len_after

### ISSUE THREAD

**Issue by magland** [colehurwitz31/spikeinterface#35]
snippet_len_before and snippet_len_after is cumbersome, I'd rather just have

snippet_len

which would be a single integer, with the option of passing in a 2-vector, which would represent the [len_before, len_after]

**Comment by colehurwitz31** [comment]
So how would this be implemented in the arguments?

**Comment by colehurwitz31** [comment]
Ok. That looks alright. I can do that on the Cole branch today and change the unit tests.

**Comment by colehurwitz31** [comment]
I think snippet_offset can be added or subtracted from the reference frame before being passed into get snippets. So we should just keep reference frames and have the user pass in: spike_peaks - offset if they want.

**Comment by mhhennig** [comment]
Yes, good point!
