### ISSUE TITLE
MEArec notebook bug

### ISSUE THREAD

**Issue by colehurwitz31** [colehurwitz31/spikeinterface#54]
So when I run the demo_mearec_extractors, it appears to have an issues:

```
print("Number of recording channels: %d" %rext.getNumChannels())
print("Number of frames recorded: %d" %rext.getNumFrames())
print("Sampling frequency: %f" %rext.getSamplingFrequency())
print("Location channel 0:", rext.getChannelProperty(0, 'location'))
print("Number of units = "+str(len(sext.getUnitIds())))
```
--> 234     return rec_dict, info
"local variable 'info' referenced before assignment"
Is that an issue on my end or in the extractor Alessio?

**Comment by alejoe91** [comment]
In which line @colehurwitz31 ? I mean in the noetebook
